name: Deploy to EC2
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2 by using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          if [ ! -d "/home/ubuntu/doni-alta-rds" ]
          then
            git clone git@github.com:pebruwantoro/doni-alta-rds.git /home/ubuntu/doni-alta-rds 
          fi
          cd /home/ubuntu/doni-alta-rds
          git pull origin master
          docker stop  donpebru/trialrds:latest
          docker rm  donpebru/trialrds:latest
          cd program
          docker build -t donpebru/trialrds:latest .
          docker run -d -e "HTTP_PORT=:80" -e "CONNECTION_STRING=root:02021996Doni*@tcp(18.142.49.198:3306)/alta_db?charset=utf8mb4&parseTime=True&loc=Local" -p 80:80 --name cobards donpebru/cobards:latest
